### ISSUE TITLE
Cannot Import GeneFinder from Pyrodigal since update

### ISSUE THREAD

**Issue by hb660** [labgem/PPanGGOLiN#174]
Hi,

I hope you will be able to help me. 
I wanted to update the new version of PPanggolin to can run the "all" workflow with my own annotation (from issue 172/173).

Since that I get this issue when I start to load ppanggolin from my conda environment. (It was working fine before the update, but I made the mistake to try to update in the given environnment ... trying to delete the environnement and re-install but still happen). In case you cannot find a solve to this issue, I will install the previous version and try the step by step but in case other users have it.
I am working in Linux environnement Ubuntu 22.04.3 LTS

"(PPanggolin) hbhome@ldf1:~$ ppanggolin -h
Traceback (most recent call last):
  File "/home/helenebouras/anaconda3/envs/PPanggolin/bin/ppanggolin", line 7, in <module>
    from ppanggolin.main import main
  File "/home/helenebouras/anaconda3/envs/PPanggolin/lib/python3.10/site-packages/ppanggolin/__init__.py", line 5, in <module>
    import ppanggolin.annotate
  File "/home/helenebouras/anaconda3/envs/PPanggolin/lib/python3.10/site-packages/ppanggolin/annotate/__init__.py", line 1, in <module>
    from .annotate import subparser, launch
  File "/home/helenebouras/anaconda3/envs/PPanggolin/lib/python3.10/site-packages/ppanggolin/annotate/annotate.py", line 17, in <module>
    from ppanggolin.annotate.synta import (annotate_organism, read_fasta, get_dna_sequence,
  File "/home/helenebouras/anaconda3/envs/PPanggolin/lib/python3.10/site-packages/ppanggolin/annotate/synta.py", line 17, in <module>
    from pyrodigal import GeneFinder, Sequence
ImportError: cannot import name 'GeneFinder' from 'pyrodigal' (/home/helenebouras/.local/lib/python3.10/site-packages/pyrodigal/__init__.py) "

I tried also from my python interface in the terminal and I have the same issue. I updated pip and conda and still the same issue. Tried to re-install Pyrodigal on my own computer but it does not solve it. Do the issue come pyrodigal ?
As the update of ppanggolin is very recent and I install via conda to ensure to have all repositories at the version needed for its proper functionment, I post here. Please tell me if I should rather send this issue to prodigal page.

Thanks a lot in advance
Best regards
Helene

**Comment by axbazin** [comment]
Hi,

Thank you for this issue !
There is probably an unexpected mismatch between versions of pyrodigal and ppanggolin somewhere. ppanggolin needs at least pyrodigal 3.0 or above.

From what you are saying I understand that this is with ppanggolin v2.0.2 (if you can show the output of "ppanggolin --version" that would be ideal). 
Could you also show which version of pyrodigal is installed here?
To do this, you can launch a python instance, then run:

```python
import pyrodigal
print(pyrodigal.__version__)
```
It should show "3.3.0" (this is both what my working version shows, and what our CI tests), if not then there may be an issue with our conda recipe or the installation procedure or something like that.

Best,
Adelme

**Comment by axbazin** [comment]
I would have expected the same thing as you did. Just to make sure I checked the recipe in bioconda and everything is fine, it requires pyrodigal to be above 3.0, so I don't know what happened, it is strange.

Glad it works now !

Adelme

**Comment by jpjarnoux** [comment]
Hi
Thanks for using PPanGGOLiN.
I know that everything works now, but in order to help other users, I would to know if you were using PPanGGOLiN in its own environment or if you installed it in an environment with other tools ? 
We recommend installing PPanGGOLiN in its own environment to be sure that no other packages can create a compatibility problem.
Jérôme
